// Curated list of fruits and nuts for the add-fruit autocomplete.
// Common names only — no varieties (e.g. "apple" not "Macintosh apple").
// Keep sorted alphabetically for readability; the autocomplete filters dynamically.

export const FRUIT_LIST = [
  // Tree fruit
  'apple',
  'apricot',
  'asian pear',
  'cherry',
  'crabapple',
  'fig',
  'loquat',
  'medlar',
  'mulberry',
  'nectarine',
  'pawpaw',
  'peach',
  'pear',
  'persimmon',
  'plum',
  'pluot',
  'quince',
  'serviceberry',
  'sour cherry',

  // Citrus
  'bergamot',
  'blood orange',
  'calamansi',
  'citron',
  'clementine',
  'grapefruit',
  'kumquat',
  'lemon',
  'lime',
  'mandarin',
  'orange',
  'pomelo',
  'tangerine',
  'yuzu',

  // Tropical / subtropical
  'avocado',
  'banana',
  'breadfruit',
  'cherimoya',
  'dragon fruit',
  'feijoa',
  'guava',
  'jackfruit',
  'jaboticaba',
  'longan',
  'lychee',
  'mango',
  'papaya',
  'passion fruit',
  'rambutan',
  'sapote',
  'soursop',
  'starfruit',
  'surinam cherry',
  'tamarind',

  // Nuts
  'almond',
  'chestnut',
  'hazelnut',
  'macadamia',
  'pecan',
  'pine nut',
  'pistachio',
  'walnut',

  // Berries / vines
  'blackberry',
  'blueberry',
  'boysenberry',
  'cranberry',
  'currant',
  'dewberry',
  'elderberry',
  'gooseberry',
  'grape',
  'huckleberry',
  'kiwi',
  'loganberry',
  'raspberry',
  'strawberry',

  // Other
  'coconut',
  'date',
  'jujube',
  'olive',
  'pomegranate',
  'prickly pear',
];
