// Curated list of forageable items for the add-a-find autocomplete.
// Common names only — no varieties (e.g. "apple" not "Macintosh apple").
// Keep sorted alphabetically for readability; the autocomplete filters dynamically.

export const FRUIT_LIST = [
  // Tree fruit
  'apple',
  'apricot',
  'asian pear',
  'cherry',
  'crabapple',
  'fig',
  'loquat',
  'medlar',
  'mulberry',
  'nectarine',
  'pawpaw',
  'peach',
  'pear',
  'persimmon',
  'plum',
  'pluot',
  'quince',
  'serviceberry',
  'sour cherry',

  // Citrus
  'bergamot',
  'blood orange',
  'calamansi',
  'citron',
  'clementine',
  'grapefruit',
  'kumquat',
  'lemon',
  'lime',
  'mandarin',
  'orange',
  'pomelo',
  'tangerine',
  'yuzu',

  // Tropical / subtropical
  'avocado',
  'banana',
  'breadfruit',
  'cherimoya',
  'dragon fruit',
  'feijoa',
  'guava',
  'jackfruit',
  'jaboticaba',
  'longan',
  'lychee',
  'mango',
  'papaya',
  'passion fruit',
  'rambutan',
  'sapote',
  'soursop',
  'starfruit',
  'surinam cherry',
  'tamarind',

  // Nuts
  'almond',
  'chestnut',
  'hazelnut',
  'macadamia',
  'pecan',
  'pine nut',
  'pistachio',
  'walnut',

  // Berries / vines
  'aronia',
  'autumn olive',
  'blackberry',
  'blueberry',
  'boysenberry',
  'cranberry',
  'currant',
  'dewberry',
  'elderberry',
  'gooseberry',
  'grape',
  'hawthorn',
  'huckleberry',
  'kiwi',
  'loganberry',
  'raspberry',
  'rose hip',
  'strawberry',
  'wintergreen',

  // Other
  'coconut',
  'date',
  'jujube',
  'olive',
  'pomegranate',
  'prickly pear',

  // Mushrooms
  'black trumpet',
  'cauliflower mushroom',
  'chanterelle',
  'chicken of the woods',
  'giant puffball',
  'hedgehog mushroom',
  'hen of the woods',
  'lion\'s mane',
  'lobster mushroom',
  'matsutake',
  'meadow mushroom',
  'morel',
  'oyster mushroom',
  'porcini',
  'shaggy mane',
  'turkey tail',
  'wine cap',

  // Herbs & Wild Greens
  'burdock',
  'cattail',
  'chickweed',
  'chicory',
  'dandelion',
  'fiddlehead fern',
  'field garlic',
  'garlic mustard',
  'jerusalem artichoke',
  'lambsquarters',
  'mallow',
  'miner\'s lettuce',
  'nettles',
  'plantain',
  'purslane',
  'ramps',
  'sheep sorrel',
  'spicebush',
  'violet',
  'watercress',
  'wild bergamot',
  'wild ginger',
  'wild mint',
  'wild onion',
  'wood sorrel',
  'yarrow',
];
