// Curated list of forageable items for the add-a-find autocomplete.
// Common names only — no varieties (e.g. "apple" not "Macintosh apple").
// Keep sorted alphabetically for readability; the autocomplete filters dynamically.

export const FRUIT_LIST = [
  // Tree fruit
  'apple',
  'apricot',
  'asian pear',
  'cherry',
  'crabapple',
  'fig',
  'loquat',
  'medlar',
  'mulberry',
  'nectarine',
  'pawpaw',
  'peach',
  'pear',
  'persimmon',
  'plum',
  'pluot',
  'quince',
  'serviceberry',
  'sour cherry',

  // Citrus
  'bergamot',
  'blood orange',
  'calamansi',
  'citron',
  'clementine',
  'grapefruit',
  'kumquat',
  'lemon',
  'lime',
  'mandarin',
  'orange',
  'pomelo',
  'tangerine',
  'yuzu',

  // Tropical / subtropical
  'avocado',
  'banana',
  'breadfruit',
  'cherimoya',
  'dragon fruit',
  'feijoa',
  'guava',
  'jackfruit',
  'jaboticaba',
  'longan',
  'lychee',
  'mango',
  'papaya',
  'passion fruit',
  'rambutan',
  'sapote',
  'soursop',
  'starfruit',
  'surinam cherry',
  'tamarind',

  // Nuts
  'almond',
  'chestnut',
  'hazelnut',
  'macadamia',
  'pecan',
  'pine nut',
  'pistachio',
  'walnut',

  // Berries / vines
  'aronia',
  'autumn olive',
  'blackberry',
  'blueberry',
  'boysenberry',
  'cranberry',
  'currant',
  'dewberry',
  'elderberry',
  'gooseberry',
  'grape',
  'hawthorn',
  'huckleberry',
  'kiwi',
  'loganberry',
  'raspberry',
  'rose hip',
  'strawberry',
  'wintergreen',

  // Other
  'coconut',
  'date',
  'jujube',
  'olive',
  'pomegranate',
  'prickly pear',

  // Mushrooms
  'black trumpet',
  'cauliflower mushroom',
  'chanterelle',
  'chicken of the woods',
  'giant puffball',
  'hedgehog mushroom',
  'hen of the woods',
  'lion\'s mane',
  'lobster mushroom',
  'matsutake',
  'meadow mushroom',
  'morel',
  'oyster mushroom',
  'porcini',
  'shaggy mane',
  'turkey tail',
  'wine cap',

  // Culinary Herbs (garden-grown or semi-wild, hand-harvestable)
  'basil',
  'bay laurel',
  'borage',
  'chamomile',
  'chervil',
  'chives',
  'cilantro',
  'curry leaf',
  'dill',
  'epazote',
  'fennel',
  'holy basil',
  'hyssop',
  'lavender',
  'lemon verbena',
  'lovage',
  'marjoram',
  'mint',
  'oregano',
  'parsley',
  'perilla',
  'rosemary',
  'rue',
  'sage',
  'shiso',
  'sorrel',
  'summer savory',
  'stevia',
  'tarragon',
  'thyme',
  'vietnamese coriander',
  'winter savory',

  // Wild Plants & Greens
  'anise hyssop',
  'burdock',
  'catnip',
  'cattail',
  'chickweed',
  'chicory',
  'cleavers',
  'dandelion',
  'fiddlehead fern',
  'field garlic',
  'garlic mustard',
  'ground ivy',
  'jerusalem artichoke',
  'lambsquarters',
  'lemon balm',
  'mallow',
  'miner\'s lettuce',
  'nettles',
  'plantain',
  'purslane',
  'ramps',
  'sheep sorrel',
  'spicebush',
  'sweet cicely',
  'violet',
  'watercress',
  'wild bergamot',
  'wild ginger',
  'wild mint',
  'wild onion',
  'wood nettle',
  'wood sorrel',
  'yarrow',
];
